/**
 * Canonical icon-name list (no JSX) — safe to import from metadata and the
 * Node manifest generator. `icons.tsx` provides the matching drawings and is
 * type-checked against this union.
 */
export const iconNames = [
  'check',
  'close',
  'chevron-down',
  'chevron-up',
  'chevron-left',
  'chevron-right',
  'search',
  'plus',
  'minus',
  'info',
  'alert-triangle',
  'alert-circle',
  'check-circle',
  'x-circle',
  'user',
  'home',
  'settings',
  'menu',
  'arrow-right',
  'arrow-left',
  'external-link',
  'eye',
  'eye-off',
  'heart',
  'star',
  'bell',
  'calendar',
  'mail',
  'lock',
  'trash',
  'edit',
  'download',
  'upload',
  'more-horizontal',
  'more-vertical',
  'loader',
  'sun',
  'moon',
  // Directional
  'arrow-up',
  'arrow-down',
  // Media
  'play',
  'pause',
  'stop',
  'skip-forward',
  'skip-back',
  'volume',
  'camera',
  'video',
  'mic',
  'image',
  // Files
  'file',
  'folder',
  'clipboard',
  'copy',
  'save',
  'paperclip',
  // Commerce
  'shopping-cart',
  'credit-card',
  'gift',
  'dollar-sign',
  // Communication
  'message-circle',
  'send',
  'phone',
  'share',
  'at-sign',
  // Status / actions
  'help-circle',
  'zap',
  'flag',
  'bookmark',
  'thumbs-up',
  'thumbs-down',
  'award',
  'shield',
  // Layout / navigation
  'grid',
  'list',
  'filter',
  'refresh',
  'sliders',
  'maximize',
  'minimize',
  'log-in',
  'log-out',
  // System / data
  'globe',
  'map-pin',
  'clock',
  'wifi',
  'cloud',
  'code',
  'terminal',
  'database',
  'server',
  'activity',
  'trending-up',
  'bar-chart',
  'pie-chart',
  'git-branch',
  // People
  'users',
  'user-plus',
  // Misc
  'coffee',
  // Sort / table / data-grid
  'chevrons-up-down',
  'chevrons-up',
  'chevrons-down',
  'chevrons-left',
  'chevrons-right',
  'columns',
  'table',
  'layout',
  // Selection
  'square',
  'check-square',
  'x-square',
  'circle',
  'dot',
  'plus-circle',
  'minus-circle',
  // Filters / drag
  'filter-x',
  'grip-vertical',
  'grip-horizontal',
  // Actions
  'rotate-ccw',
  'rotate-cw',
  'zoom-in',
  'zoom-out',
  'maximize-2',
  'minimize-2',
  // Content
  'tag',
  'hash',
  'unlock',
  'file-text',
  'printer',
  'link',
  'bell-off',
] as const;

export type IconName = (typeof iconNames)[number];
