import type { Meta, StoryObj } from '@storybook/react'
import {
  ArrowPathIcon,
  Bars3Icon,
  BellIcon,
  BookOpenIcon,
  BookmarkIcon,
  CalendarIcon,
  CameraIcon,
  ChatBubbleLeftIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ClockIcon,
  CloudIcon,
  Cog6ToothIcon,
  CreditCardIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FlagIcon,
  FolderIcon,
  GiftIcon,
  HeartIcon,
  HomeIcon,
  InformationCircleIcon,
  KeyIcon,
  LinkIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MinusIcon,
  PaperClipIcon,
  PauseCircleIcon,
  PencilIcon,
  PhoneIcon,
  PhotoIcon,
  PlayCircleIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  ShareIcon,
  ShoppingCartIcon,
  StarIcon,
  TagIcon,
  TrashIcon,
  UserIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline'
import { FIGMA_FILE } from '../shared/figma'
import { IconGallery } from './IconGallery'

const RAW = {
  BellIcon,
  BookOpenIcon,
  CalendarIcon,
  CameraIcon,
  ChatBubbleLeftIcon,
  CloudIcon,
  Cog6ToothIcon,
  HeartIcon,
  HomeIcon,
  ShoppingCartIcon,
  StarIcon,
  UserIcon,
  MagnifyingGlassIcon,
  TrashIcon,
  PencilIcon,
  PlusIcon,
  MinusIcon,
  XMarkIcon,
  CheckIcon,
  CheckCircleIcon,
  XCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  EnvelopeIcon,
  PhoneIcon,
  MapPinIcon,
  ClockIcon,
  EyeIcon,
  EyeSlashIcon,
  LockClosedIcon,
  KeyIcon,
  LinkIcon,
  ShareIcon,
  PaperClipIcon,
  FolderIcon,
  DocumentTextIcon,
  PhotoIcon,
  PlayCircleIcon,
  PauseCircleIcon,
  CreditCardIcon,
  GiftIcon,
  TagIcon,
  BookmarkIcon,
  FlagIcon,
  Bars3Icon,
  ChevronDownIcon,
  ArrowPathIcon,
}

const ITEMS = Object.entries(RAW).map(
  ([name, Icon]) =>
    [name, <Icon key={name} className="w-6 h-6" style={{ width: 24, height: 24 }} />] as const,
)

const meta = {
  title: 'Icons/Heroicons (Tailwind SVG)',
  parameters: {
    design: { type: 'figma', url: `${FIGMA_FILE}?node-id=0-1` },
  },
} satisfies Meta

export default meta
type Story = StoryObj<typeof meta>

export const Default: Story = {
  render: () => <IconGallery items={ITEMS} />,
}
