import type { Meta, StoryObj } from '@storybook/react'
import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconBell,
  IconBook,
  IconBookmark,
  IconCalendar,
  IconCamera,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconClock,
  IconCloud,
  IconCreditCard,
  IconDownload,
  IconEye,
  IconEyeOff,
  IconFileText,
  IconFilter,
  IconFlag,
  IconFolder,
  IconGift,
  IconHeart,
  IconHelp,
  IconHome,
  IconInfoCircle,
  IconKey,
  IconLink,
  IconList,
  IconLock,
  IconLockOpen,
  IconMail,
  IconMapPin,
  IconMenu2,
  IconMessageCircle,
  IconMinus,
  IconMoon,
  IconPaperclip,
  IconPencil,
  IconPhone,
  IconPhoto,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconShare,
  IconShoppingCart,
  IconStar,
  IconSun,
  IconTag,
  IconTrash,
  IconUpload,
  IconUser,
  IconWorld,
  IconX,
} from '@tabler/icons-react'
import { FIGMA_FILE } from '../shared/figma'
import { IconGallery } from './IconGallery'

// Heroicons/Lucide와 동일한 인라인 SVG 컴포넌트 방식(currentColor stroke).
const RAW = {
  IconBell,
  IconBook,
  IconCalendar,
  IconCamera,
  IconMessageCircle,
  IconCloud,
  IconSettings,
  IconHeart,
  IconHome,
  IconShoppingCart,
  IconStar,
  IconUser,
  IconSearch,
  IconTrash,
  IconPencil,
  IconPlus,
  IconMinus,
  IconX,
  IconCheck,
  IconAlertTriangle,
  IconAlertCircle,
  IconInfoCircle,
  IconHelp,
  IconMail,
  IconPhone,
  IconMapPin,
  IconClock,
  IconEye,
  IconEyeOff,
  IconLock,
  IconLockOpen,
  IconKey,
  IconLink,
  IconShare,
  IconPaperclip,
  IconFolder,
  IconFileText,
  IconPhoto,
  IconPlayerPlay,
  IconPlayerPause,
  IconCreditCard,
  IconGift,
  IconTag,
  IconBookmark,
  IconFlag,
  IconMenu2,
  IconChevronDown,
  IconChevronUp,
  IconChevronLeft,
  IconChevronRight,
  IconArrowLeft,
  IconArrowRight,
  IconRefresh,
  IconDownload,
  IconUpload,
  IconFilter,
  IconList,
  IconWorld,
  IconSun,
  IconMoon,
}

const ITEMS = Object.entries(RAW).map(
  ([name, Icon]) => [name, <Icon key={name} size={24} stroke={1.75} />] as const,
)

const meta = {
  title: 'Icons/Tabler (SVG)',
  parameters: {
    design: { type: 'figma', url: `${FIGMA_FILE}?node-id=0-1` },
  },
} satisfies Meta

export default meta
type Story = StoryObj<typeof meta>

export const Default: Story = {
  render: () => <IconGallery items={ITEMS} />,
}
