// bootstrap-icons(16그리드 filled) → figma-plugin/src/icons-data.ts 의 ICON_PATHS 생성.
// 플러그인이 Figma에 만드는 _Icon/* 컴포넌트(인스턴스 스왑 대상)의 벡터 path 소스.
// 재생성: pnpm --dir figma-plugin gen:icons
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..', '..')
const iconsDir = resolve(root, 'node_modules', 'bootstrap-icons', 'icons')

// [Figma 이름(_Icon/<Name>), bootstrap 파일 후보(존재하는 첫 번째 사용)]
// 오너 규칙: 아이콘은 "라인아트 위주" → 아웃라인(비-fill) 우선, fill은 폴백.
// Star/Heart/Bell 이름은 매니페스트 swap default·preferred가 참조하므로 유지.
const MAP = [
  ['Star', ['star', 'star-fill']],
  ['Heart', ['heart', 'heart-fill']],
  ['Bell', ['bell', 'bell-fill']],
  ['House', ['house', 'house-door', 'house-fill']],
  ['Person', ['person', 'person-fill']],
  ['Envelope', ['envelope', 'envelope-fill']],
  ['Phone', ['telephone', 'telephone-fill']],
  ['Settings', ['gear', 'gear-fill']],
  ['Calendar', ['calendar', 'calendar3', 'calendar-fill']],
  ['Clock', ['clock', 'clock-fill']],
  ['Search', ['search']],
  ['Trash', ['trash', 'trash3', 'trash-fill']],
  ['Edit', ['pencil', 'pencil-square', 'pencil-fill']],
  ['Plus', ['plus-circle', 'plus-circle-fill']],
  ['Minus', ['dash-circle', 'dash-circle-fill']],
  ['Close', ['x-circle', 'x-circle-fill']],
  ['Check', ['check-circle', 'check-circle-fill']],
  ['Info', ['info-circle', 'info-circle-fill']],
  ['Warning', ['exclamation-triangle', 'exclamation-triangle-fill']],
  ['Help', ['question-circle', 'question-circle-fill']],
  ['Camera', ['camera', 'camera-fill']],
  ['Cart', ['cart', 'cart-fill']],
  ['Chat', ['chat', 'chat-fill']],
  ['Cloud', ['cloud', 'cloud-fill']],
  ['Image', ['image', 'image-fill']],
  ['Lock', ['lock', 'lock-fill']],
  ['Eye', ['eye', 'eye-fill']],
  ['Folder', ['folder', 'folder2', 'folder-fill']],
  ['Bookmark', ['bookmark', 'bookmark-fill']],
  ['Tag', ['tag', 'tag-fill']],
  ['Flag', ['flag', 'flag-fill']],
  ['Gift', ['gift', 'gift-fill']],
  ['Download', ['download']],
  ['Upload', ['upload']],
  ['Link', ['link-45deg', 'link']],
]

const out = {}
const skipped = []
for (const [name, candidates] of MAP) {
  const file = candidates.find((c) => existsSync(resolve(iconsDir, `${c}.svg`)))
  if (!file) {
    skipped.push(name)
    continue
  }
  const svg = readFileSync(resolve(iconsDir, `${file}.svg`), 'utf8')
  const ds = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1])
  if (ds.length === 0) {
    skipped.push(name)
    continue
  }
  // 각 <path d>를 독립 문자열로 보존한다(합치지 않음). SVG 규약상 path의 첫 moveto는
  // 소문자 m이라도 절대 좌표다 — 공백으로 이어붙이면 두 번째 path가 상대 이동으로 오역된다.
  // 런타임(components.ts)에서 svgToFigmaPath로 각각 변환 후 합친다.
  out[`_Icon/${name}`] = ds
}

const ts =
  '// AUTO-GENERATED by scripts/gen-icons.mjs — bootstrap-icons 16그리드 filled path.\n' +
  '// DO NOT EDIT. 재생성: pnpm --dir figma-plugin gen:icons\n' +
  '// 값은 아이콘별 <path d> 문자열 배열(원본 그대로) — 런타임에서 Figma-safe로 변환됨.\n' +
  `export const ICON_PATHS: Record<string, string[]> = ${JSON.stringify(out, null, 2)}\n`
writeFileSync(resolve(here, '..', 'src', 'icons-data.ts'), ts)
console.log(
  `gen-icons OK — ${Object.keys(out).length} icons → figma-plugin/src/icons-data.ts` +
    (skipped.length ? ` (skipped: ${skipped.join(', ')})` : ''),
)
