// bootstrap-icons(16그리드 filled) → figma-plugin/src/icons-data.ts 의 ICON_PATHS 생성.
// 플러그인이 Figma에 만드는 _Icon/* 컴포넌트(인스턴스 스왑 대상)의 벡터 path 소스.
// 재생성: pnpm --dir figma-plugin gen:icons
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..', '..')
const iconsDir = resolve(root, 'node_modules', 'bootstrap-icons', 'icons')

// [Figma 이름(_Icon/<Name>), bootstrap 파일 후보(존재하는 첫 번째 사용)]
// Star/Heart/Bell 이름은 매니페스트 swap default·preferred가 참조하므로 유지.
const MAP = [
  ['Star', ['star-fill']],
  ['Heart', ['heart-fill']],
  ['Bell', ['bell-fill']],
  ['House', ['house-fill']],
  ['Person', ['person-fill']],
  ['Envelope', ['envelope-fill']],
  ['Phone', ['telephone-fill']],
  ['Settings', ['gear-fill']],
  ['Calendar', ['calendar-fill']],
  ['Clock', ['clock-fill']],
  ['Search', ['search']],
  ['Trash', ['trash-fill']],
  ['Edit', ['pencil-fill']],
  ['Plus', ['plus-circle-fill']],
  ['Minus', ['dash-circle-fill']],
  ['Close', ['x-circle-fill']],
  ['Check', ['check-circle-fill']],
  ['Info', ['info-circle-fill']],
  ['Warning', ['exclamation-triangle-fill']],
  ['Help', ['question-circle-fill']],
  ['Camera', ['camera-fill']],
  ['Cart', ['cart-fill']],
  ['Chat', ['chat-fill']],
  ['Cloud', ['cloud-fill']],
  ['Image', ['image-fill']],
  ['Lock', ['lock-fill']],
  ['Eye', ['eye-fill']],
  ['Folder', ['folder-fill']],
  ['Bookmark', ['bookmark-fill']],
  ['Tag', ['tag-fill']],
  ['Flag', ['flag-fill']],
  ['Gift', ['gift-fill']],
  ['Download', ['download']],
  ['Upload', ['upload']],
  ['Link', ['link-45deg', 'link']],
]

const out = {}
const skipped = []
for (const [name, candidates] of MAP) {
  const file = candidates.find((c) => existsSync(resolve(iconsDir, `${c}.svg`)))
  if (!file) {
    skipped.push(name)
    continue
  }
  const svg = readFileSync(resolve(iconsDir, `${file}.svg`), 'utf8')
  const ds = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1])
  if (ds.length === 0) {
    skipped.push(name)
    continue
  }
  out[`_Icon/${name}`] = ds.join(' ')
}

const ts =
  '// AUTO-GENERATED by scripts/gen-icons.mjs — bootstrap-icons 16그리드 filled path.\n' +
  '// DO NOT EDIT. 재생성: pnpm --dir figma-plugin gen:icons\n' +
  `export const ICON_PATHS: Record<string, string> = ${JSON.stringify(out, null, 2)}\n`
writeFileSync(resolve(here, '..', 'src', 'icons-data.ts'), ts)
console.log(
  `gen-icons OK — ${Object.keys(out).length} icons → figma-plugin/src/icons-data.ts` +
    (skipped.length ? ` (skipped: ${skipped.join(', ')})` : ''),
)
