// 소셜/브랜드 로고 → figma-plugin/src/logos-data.ts
// 오너 규칙: Storybook의 로고 SVG(src/ds/SocialLoginButton/logos/*.svg)를 그대로 이식.
// 라인아트 아이콘과 달리 브랜드 로고는 원본 FILL(다색)을 보존한다(플러그인이 fill로 렌더).
// 값 = { viewBox, paths:[{fill, d}] }. polygon은 d로 변환. 재생성: pnpm --dir figma-plugin gen:logos
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..', '..')
const logosDir = resolve(root, 'src', 'ds', 'SocialLoginButton', 'logos')
const KEYS = ['google', 'kakao', 'naver', 'facebook']

const out = {}
for (const key of KEYS) {
  const svg = readFileSync(resolve(logosDir, key + '.svg'), 'utf8')
  const vbm = svg.match(/viewBox="([^"]+)"/)
  if (!vbm) throw new Error(`${key}.svg: viewBox 없음`)
  const viewBox = vbm[1].trim().split(/[\s,]+/).map(Number)
  const paths = []

  // <path fill="..." d="..."/>  (fill이 d보다 앞)
  const pathRe = /<path\b[^>]*?\bfill="([^"]+)"[^>]*?\bd="([^"]+)"[^>]*?\/?>/g
  let m
  while ((m = pathRe.exec(svg))) paths.push({ fill: m[1], d: m[2] })

  // <polygon fill="..." points="..."/>  → d
  const polyRe = /<polygon\b[^>]*?\bfill="([^"]+)"[^>]*?\bpoints="([^"]+)"[^>]*?\/?>/g
  while ((m = polyRe.exec(svg))) {
    const pts = m[2].trim().split(/\s+/).map((p) => p.split(',').map(Number))
    const d = pts.map(([x, y], i) => `${i === 0 ? 'M' : 'L'} ${x} ${y}`).join(' ') + ' Z'
    paths.push({ fill: m[1], d })
  }

  if (!paths.length) throw new Error(`${key}.svg: path/polygon 없음`)
  out[key] = { viewBox, paths }
}

const ts =
  `// AUTO-GENERATED by scripts/gen-logos.mjs — DO NOT EDIT (SSOT: src/ds/SocialLoginButton/logos/*.svg)\n` +
  `// 브랜드/소셜 로고 원본 데이터. 아이콘(stroke)과 달리 FILL 보존으로 렌더한다(brand-logos.ts).\n` +
  `export type BrandLogo = { viewBox: [number, number, number, number]; paths: { fill: string; d: string }[] }\n` +
  `export const LOGOS_DATA: Record<string, BrandLogo> = ${JSON.stringify(out, null, 2)}\n`
writeFileSync(resolve(root, 'figma-plugin', 'src', 'logos-data.ts'), ts)
console.log(`gen-logos OK — ${KEYS.length} logos → figma-plugin/src/logos-data.ts`)
