// AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT (SSOT: tokens/*.json)
// Figma 플러그인 프리셋 데이터. presets.ts가 이 파일을 import 한다 → Storybook과 단일 소스 공유.
import type { PresetName, TokensJson } from './presets'

export const PRESET_DATA: Record<PresetName, TokensJson> = {
  "bootstrap": {
    "$preset": "bootstrap",
    "color": {
      "primary": "#7952B3",
      "secondary": "#6C757D",
      "error": "#DC3545",
      "success": "#198754",
      "warning": "#FFC107",
      "bg": "#FFFFFF",
      "bgSubtle": "#F8F9FA",
      "text": "#212529",
      "border": "#DEE2E6"
    },
    "typography": {
      "fontFamily": "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
      "baseSize": 16,
      "scale": 1.25,
      "sizes": {
        "xs": 10,
        "sm": 13,
        "md": 16,
        "lg": 20,
        "xl": 25,
        "xxl": 31
      },
      "weights": {
        "regular": 400,
        "medium": 500,
        "bold": 700
      }
    },
    "radius": {
      "sm": 4,
      "md": 8,
      "lg": 12
    },
    "spacing": {
      "1": 4,
      "2": 8,
      "3": 12,
      "4": 16,
      "5": 20,
      "6": 24
    }
  },
  "tailwind": {
    "$preset": "tailwind",
    "color": {
      "primary": "#06B6D4",
      "secondary": "#64748B",
      "error": "#EF4444",
      "success": "#22C55E",
      "warning": "#F59E0B",
      "bg": "#FFFFFF",
      "bgSubtle": "#F9FAFB",
      "text": "#0F172A",
      "border": "#E5E7EB"
    },
    "typography": {
      "fontFamily": "'Inter', system-ui, sans-serif",
      "baseSize": 16,
      "scale": 1.25,
      "sizes": {
        "xs": 10,
        "sm": 13,
        "md": 16,
        "lg": 20,
        "xl": 25,
        "xxl": 31
      },
      "weights": {
        "regular": 400,
        "medium": 500,
        "bold": 700
      }
    },
    "radius": {
      "sm": 4,
      "md": 8,
      "lg": 12
    },
    "spacing": {
      "1": 4,
      "2": 8,
      "3": 12,
      "4": 16,
      "5": 20,
      "6": 24
    }
  },
  "toss": {
    "$preset": "toss",
    "color": {
      "primary": "#3D6BFF",
      "secondary": "#4E5968",
      "error": "#F04452",
      "success": "#00C471",
      "warning": "#FF9F0A",
      "bg": "#FFFFFF",
      "bgSubtle": "#F5F7FA",
      "text": "#191F28",
      "border": "#E5E8EB"
    },
    "typography": {
      "fontFamily": "'Pretendard', -apple-system, sans-serif",
      "baseSize": 16,
      "scale": 1.2,
      "sizes": {
        "xs": 11,
        "sm": 13,
        "md": 16,
        "lg": 19,
        "xl": 23,
        "xxl": 28
      },
      "weights": {
        "regular": 400,
        "medium": 500,
        "bold": 700
      }
    },
    "radius": {
      "sm": 4,
      "md": 8,
      "lg": 12
    },
    "spacing": {
      "1": 4,
      "2": 8,
      "3": 12,
      "4": 16,
      "5": 20,
      "6": 24
    }
  }
}
