/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증 (세션 발급) — BE-001-EP-01
         * @description 근거 FS: FS-001-EL-016. **익명(미인증) 호출 전용**이며 역할 판정이 없다.
         *
         *     - **멱등**하다. 세션 레코드를 서버에 만들지 않고 응답 바디로만 전달한다. `Set-Cookie` 를 발급하지 않는다
         *       (abort 이후 세션 발급 경합 차단 — BE-001 §4 타임아웃 규칙 1·2).
         *     - 이 엔드포인트는 **`UNAUTHENTICATED` 를 반환하지 않는다** (BE-001 §3.3). 401 은
         *       `INVALID_CREDENTIALS` 1종뿐이며 의미는 '인증 시도 실패'다 — 프론트는 리다이렉트하지 않는다.
         *     - 미등록 이메일 · 오답 비밀번호 · 비활성 계정의 오답은 **완전히 동일한 401 응답**이다 (계정 열거 오라클 차단).
         *     - 서버 인증 처리 상한 5초 (프론트 10초 `LOGIN_TIMEOUT_MS` 보다 먼저 끊는다).
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/tabs/{tab}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 탭 데이터 조회 — BE-002-EP-01
         * @description 근거 FS: FS-002-EL-014. 멱등 (GET). 페이징 없음 — 행 수가 계약 상한으로 고정된다.
         *
         *     **서버가 기능 권한을 재판정한다** (BE-002 §3.4). 브라우저 저장소의 권한 값은 보안 경계가 아니다.
         *     요청 파라미터로 권한 키를 받지 않는 이유가 이것이다.
         *
         *     권한 소거 규칙:
         *     - `dashboard.tab.{tab}` OFF → 403 `TAB_FORBIDDEN`
         *     - `dashboard.todo` **및** `dashboard.lists` 둘 다 OFF → 403 `WIDGET_FORBIDDEN`
         *     - 한쪽만 OFF → **200 + 부분 소거** (`todos: []` 또는 `cards[].rows: []` · `cards[].count: 0`).
         *       전체 403 으로 막으면 권한 있는 위젯의 데이터까지 잃고 프론트가 실패 배너를 띄운다(오탐).
         *
         *     **404 를 어떤 조건에서도 반환하지 않는다** (BE-002 §3.3). 열거값 밖의 `tab` 은 400 이다.
         */
        get: operations["getDashboardTab"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 통계 조회 — BE-002-EP-02
         * @description 근거 FS: FS-002-EL-027. 멱등 (GET). 페이징 없음.
         *
         *     **엔드포인트를 1개로 유지한다** — 방문자 카드와 기간별 분석 카드는 화면상 2개 위젯이지만
         *     조회는 1건이다 (FS-002-EL-027). 프론트 어댑터도 `fetchStats` 1개다.
         *
         *     `range` 가 열거값 밖이면 **400 을 반환하고 조용히 폴백하지 않는다** — 폴백하면 클라이언트 버그가
         *     은폐되고 사용자가 선택하지 않은 기간의 데이터를 본다.
         *
         *     권한 소거: 방문자·기간별 분석이 **둘 다** OFF → 403 `WIDGET_FORBIDDEN`.
         *     한쪽만 OFF → 200 + 부분 소거 (`visitors: []` 또는 `periodRows: []` · `summaries: []`).
         */
        get: operations["getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 목록 조회 — BE-003-EP-01
         * @description 근거 FS: FS-003-EL-003·004·007·008·010·011·014·015. 멱등 (GET). 권한: `admin` · `operator`.
         *     레이트리밋: 관리자당 분당 120회.
         *
         *     - `tier` 와 `groupId` 가 둘 다 `all` 이 아니면 **AND** 로 결합한다 (FS-003-EL-007).
         *     - `page` 가 총 페이지 수를 넘으면 `members` 는 빈 배열, `total` 은 실제 건수다.
         *       **서버는 페이지를 자동 보정하지 않는다** (FS-003 §7 #6).
         *     - `counts` · `groupCounts` 는 **검색·필터와 무관하게 전체 회원 기준**이다 —
         *       좌측 필터 배지가 검색할 때마다 흔들리면 안 된다 (FS-003-EL-003 비고).
         *     - 소프트 삭제된(탈퇴) 회원은 즉시 제외된다 (BE-003 §7.1).
         */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 목록 내보내기 조회 — BE-003-EP-04
         * @description 근거 FS: FS-003-EL-009. 멱등 (GET). 권한: `admin` · `operator`.
         *     레이트리밋: 관리자당 **분당 3회** (전량 스캔이라 목록 조회보다 강하게 제한한다).
         *     서버 처리 상한 **30초**.
         *
         *     - **페이징 없음 — 조건에 걸린 전량을 1회 응답으로 반환한다.** 동기 응답 상한 **50,000행**,
         *       초과 시 422 `EXPORT_TOO_LARGE` (BE-003 §7.2). 잘라서 일부만 주지 않는다 —
         *       조용히 잘린 CSV 는 잘못된 운영 판단으로 이어진다.
         *     - **CSV 는 서버가 만들지 않는다.** 프론트 `toCsv(members)` 가 브라우저에서 직렬화한다.
         *       응답은 봉투 없이 `Member[]` 배열 그 자체다.
         *     - `page` · `size` 를 받지 않는다 — 내보내기는 현재 페이지가 아니라 **조건에 걸린 전체**다.
         */
        get: operations["exportMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/member-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 그룹 목록 조회 — BE-003-EP-02
         * @description 근거 FS: FS-003-EL-004. 멱등 (GET). 권한: `admin` · `operator`. 레이트리밋: 분당 60회.
         *
         *     - 페이징 없음 — 전량 반환. **그룹 수 상한 200개** (BE-003 §7.5).
         *     - **`type=member` 그룹만 반환한다.** `type=staff`(운영진) 그룹은 `/users/admins` 도메인이
         *       소비하며 회원 목록 필터에 노출되지 않는다 (BE-003 §7.4).
         *     - 그룹 id `none`('그룹 없음')은 가입 직후 기본값이며 **항상 첫 항목**이다. 삭제할 수 없다 —
         *       그룹 삭제 API 는 이 계약에 존재하지 않는다.
         */
        get: operations["listMemberGroups"];
        put?: never;
        /**
         * 회원 그룹 생성 — BE-003-EP-03
         * @description 근거 FS: FS-003-EL-016.11. 권한: **`admin` 만** (`operator` → 403). 레이트리밋: 분당 10회.
         *
         *     - **비멱등. 멱등키를 요구하지 않는다** — 그룹명 유니크 제약(409 `GROUP_NAME_DUPLICATED`)이
         *       중복 생성을 차단한다 (BE-003 §7.3). 재시도로 409 가 오면 그룹은 이미 생성된 상태다.
         *     - 그룹명 중복은 **같은 `type` 안에서만** 금지한다 (정규화: 앞뒤 공백 제거 + 대소문자 무시).
         *     - `type=staff` 로 만든 그룹은 `GET /member-groups` 응답에 **나타나지 않는다** (§7.4 — 의도된 동작).
         *     - `shippingBenefit` 은 그룹에 저장되어 주문 도메인이 소비한다. 응답 스키마에 노출하지 않는다
         *       (프론트 `MemberGroup` = `{ id, label }`).
         */
        post: operations["createMemberGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        /**
         * 회원 상세 조회 — BE-004-EP-01
         * @description 근거 FS: FS-004-EL-004~009·011. 멱등 (GET). 권한: `admin` · `operator`. 레이트리밋: 분당 120회.
         *
         *     - `pointHistory` 는 **최근 3개월(90일)** 로 서버가 범위를 제한한다 (FS-004-EL-007.10).
         *       단, `points`(잔액)는 **전체 이력의 합**이며 3개월 범위에 갇히지 않는다.
         *     - `pointHistory` 는 **취소된 내역과 그 상쇄 거래를 둘 다 제외한다** (BE-004 §7.2) —
         *       화면의 표가 프론트의 낙관적 제거 결과와 정확히 일치하고, 새로고침해도 달라지지 않는다.
         *     - **`password` 를 응답에 포함하지 않는다.** 프론트는 자리표시자만 표시한다 (FS-004-EL-004.7).
         *     - 404 `MEMBER_NOT_FOUND` 는 **없는 id · 삭제(탈퇴)된 회원 · 읽기 권한 없음(은닉)** 을 구분하지 않는다
         *       (BE-004 §3.2). 구분하면 삭제 이력과 id 존재가 노출된다.
         *     - **응답 `ETag` 는 `memo` 필드의 버전만 반영한다** (BE-004 §7.4). 적립금·활동 변경은 ETag 를
         *       바꾸지 않는다 — 응답 전체 해시를 쓰면 남이 적립금만 조정해도 메모 저장이 409 로 실패하는
         *       **가짜 충돌**이 생긴다. 어댑터가 이 값을 보관해 `PUT /members/{id}/memo` 의 `If-Match` 로 싣는다.
         */
        get: operations["getMemberDetail"];
        put?: never;
        post?: never;
        /**
         * 회원 삭제 — BE-003-EP-05
         * @description 근거 FS: FS-003-EL-011.12.1 · FS-003-EL-017.4 · FS-004-EL-002.1 · FS-004-EL-014.4.
         *     권한: **`admin` 만** (`operator` → 403). 레이트리밋: 분당 10회.
         *
         *     - **멱등**. 이미 삭제된 회원에 재요청하면 상태를 바꾸지 않고 204 를 반환한다 —
         *       삭제 이력을 노출하지 않고 프론트의 경합 성공 처리와 일치시킨다. **멱등키가 필요 없다.**
         *       404 는 **존재한 적 없는 id** 에만 반환한다.
         *     - **소프트 삭제**다 (BE-003 §7.1) — 주문·문의·구매평이 회원을 참조하고 전자상거래 기록은
         *       법정 보존 대상이다. 개인정보는 탈퇴 30일 후 비식별 처리한다 (분쟁 대응 창구이며 복구 창구가 아니다).
         *     - **되돌릴 수 없다. 복구 엔드포인트는 이 계약에 존재하지 않는다** —
         *       FS-003-EL-017.1 이 사용자에게 '이 작업은 되돌릴 수 없습니다.' 라고 고지한다.
         *     - 삭제 행위는 감사 로그에 남긴다 (행위자 · 대상 · 시각 · IP · traceId).
         */
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 비밀번호 변경 — BE-004-EP-02
         * @description 근거 FS: FS-004-EL-013.9. 권한: **`admin` 만** (`operator` → 403).
         *     레이트리밋: **관리자당 분당 5회 + 회원당 시간당 3회** (대량 계정 탈취 차단 — BE-004 §7.3).
         *
         *     **멱등** (전면 대체 쓰기). 낙관적 잠금이 불필요하다 — 이전 값에 의존하지 않는다.
         *
         *     **필수 부수 효과 3종 (선택 사항이 아니라 계약의 일부 — BE-004 §7.3)**:
         *     1. **감사 로그** — 행위자·대상·시각·IP·traceId. 비밀번호 값·해시는 남기지 않는다. 삭제할 수 없다.
         *     2. **회원 통보(메일)** — '관리자에 의해 비밀번호가 변경되었습니다'. **거래성 알림이므로 마케팅
         *        수신 미동의 회원에게도 발송한다.** 통보 실패가 비밀번호 변경을 되돌리지 않는다.
         *     3. **기존 세션·리프레시 토큰 전면 무효화** — 계정이 이미 탈취된 상황에서 비밀번호만 바꾸고
         *        공격자의 살아 있는 세션을 남기면 이 기능이 계정 복구 수단이 되지 못한다.
         *
         *     '새 비밀번호 확인'(FS-004-EL-013.5)은 **프론트 전용 검증**이며 서버로 전송되지 않는다.
         */
        patch: operations["changeMemberPassword"];
        trace?: never;
    };
    "/members/{id}/points": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 적립금 지급 / 차감 — BE-004-EP-03
         * @description 근거 FS: FS-004-EL-007.5. 권한: **`admin` 만** (`operator` → 403). 레이트리밋: 분당 30회.
         *
         *     **적립금은 돈이다 (BE-004 §7.1)**:
         *     - **`Idempotency-Key` 헤더 필수** (UUID v4, 보존 24시간). 같은 키 + 같은 바디 → **최초 응답을
         *       그대로 재생**한다 (중복 지급 없음). 같은 키 + 다른 바디 → 409 `IDEMPOTENCY_CONFLICT`.
         *       **키 누락 → 400.** 선택 사항으로 두면 실수로 누락된 요청이 정확히 위험한 요청이 된다.
         *     - **음수 잔액을 허용하지 않는다.** 차감액 > 잔액이면 422 `INSUFFICIENT_POINTS` 로 **거절**하며
         *       잔액만큼만 부분 차감하지 않는다. 잔액 검사와 차감은 **같은 원자 연산**이다 —
         *       프론트의 사전 검증은 화면이 든 잔액 기준이라 신뢰할 수 없다.
         *     - **낙관적 잠금은 불필요하다** — 증분 연산이라 두 관리자의 동시 조정이 순서와 무관하게 둘 다 유효하다.
         *     - 지급 후 잔액 상한 **100,000,000 포인트** (422 `BALANCE_LIMIT_EXCEEDED`) — 오타(0 하나 더)를 막는다.
         *
         *     **응답에 잔액(`points`)을 포함하지 않는다** — 프론트가 `Promise<PointEntry>` 를 기대하고
         *     증감분만큼 화면 잔액을 갱신한다. 잔액을 실으면 어댑터 반환 타입이 바뀐다 (BE-004 §7.5 · §7.6 #2).
         */
        post: operations["addPointEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}/points/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
                /** @description 적립금 내역 id (`PointEntry.id`). **이 회원의 내역이 아니면 404** (내역 id 열거 차단). */
                entryId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 적립금 내역 취소 — BE-004-EP-04
         * @description 근거 FS: FS-004-EL-007.8. 권한: **`admin` 만** (`operator` → 403). 레이트리밋: 분당 30회.
         *
         *     **멱등**. 이미 취소된 내역에 재요청하면 **잔액을 다시 되돌리지 않고** 204 를 반환한다.
         *
         *     **이력을 지우지 않는다 — 상쇄 거래(reversal)로 취소한다 (BE-004 §7.2)**:
         *     적립금은 회사가 회원에게 지고 있는 부채다. 원장 행을 지우면 '누가 언제 얼마를 지급했다가
         *     되돌렸는가'를 재구성할 수 없고, 부정 지급 후 흔적을 지우는 경로가 열린다.
         *     - 원장: 대상 내역을 '취소됨'으로 표시하고 **반대 부호 상쇄 거래를 추가 기록**한다. 원본은 남는다.
         *     - 조회 응답: **취소된 내역과 상쇄 거래를 둘 다 제외**한다 → 화면의 표가 프론트의 낙관적 제거
         *       결과와 정확히 일치하고 새로고침해도 달라지지 않는다.
         *
         *     **`orderNo` 가 `null` 인 내역(수기 조정)만 취소할 수 있다.** 주문 연동 적립을 회원 화면에서
         *     되돌리면 주문 도메인의 적립 기록과 어긋난다 — 회수는 주문 취소 흐름의 책임이다.
         */
        delete: operations["removePointEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}/memo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 관리자 메모 저장 — BE-004-EP-05
         * @description 근거 FS: FS-004-EL-009 · FS-004-EL-009.3. 권한: `admin` **및 `operator`**
         *     (메모는 운영 주석이므로 조회 권한자에게 허용한다 — BE-004 §3.1). 레이트리밋: 분당 30회.
         *     **403 `FORBIDDEN` 이 이 엔드포인트에 없다** — 그 밖의 역할은 404 로 은닉된다.
         *
         *     **멱등** (PUT — 전면 대체). 빈 문자열 저장을 허용한다 (메모를 비워서 저장할 수 있다).
         *     앞뒤 공백을 제거하지 않는다.
         *
         *     **낙관적 잠금이 필요한 유일한 엔드포인트다 (BE-004 §7.4)** — `If-Match` 헤더 필수.
         *     메모는 **이전 값을 읽고 고쳐 쓰는** 값이다. A 가 연 화면의 메모와 B 가 저장한 메모가 다르면
         *     A 가 저장하는 순간 **B 의 문장이 통째로 사라진다.** 잃어버리는 의도가 있으므로 충돌을 감지한다.
         */
        put: operations["saveMemberMemo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 알림 발송 — BE-003-EP-06
         * @description 근거 FS: FS-003-EL-011.12.2 · FS-004-EL-002.2. 권한: **`admin` 만** (`operator` → 403).
         *     레이트리밋: 관리자당 분당 30회 + **회원당 시간당 5회** (수신자 기준 상한을 함께 건다).
         *
         *     **바디가 없다** — 알림 내용·채널을 고르는 UI 가 화면에 없다. 채널은 **E-Mail 고정**이며
         *     내용은 서버가 보유한 운영 알림 템플릿을 쓴다.
         *
         *     - **비멱등이지만 서버가 중복을 흡수한다**: 같은 (관리자, 회원) 조합의 요청이 **60초 창** 안에
         *       다시 오면 새로 발송하지 않고 최초 요청의 202 를 재생한다. 프론트에 중복 클릭 차단이 없으므로
         *       서버가 방어한다. `Idempotency-Key` 를 보내면 그 키를 우선한다 (보존 24시간).
         *     - **비동기(작업 큐)다 (BE-003 §7.6). 202 는 접수(accept)만 보장한다** —
         *       메일 서버 도달·수신함 배달을 보장하지 않는다. 동기로 붙이면 외부 메일 게이트웨이 지연이
         *       관리자 화면의 응답 시간이 된다. 큐는 실패 시 지수 백오프로 최대 3회 재시도한다.
         *     - **발송 실패(바운스)는 이 응답으로 알리지 않는다.** 다만 **발송 전에 판정 가능한 거절 사유**
         *       (수신 미동의 · 탈퇴 회원)는 202 를 주기 전에 422 · 404 로 즉시 응답한다.
         */
        post: operations["sendMemberNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorEnvelope
         * @description **모든 4xx / 5xx 응답은 이 봉투를 따른다. 예외 없다.**
         *     엔드포인트별로 다른 응답 형식을 정의하지 않는다 — 도메인마다 다른 에러 형식을 만들면
         *     백엔드가 두 벌을 구현하게 된다 (BE-003 §2 · BE-004 §2 머리말).
         */
        ErrorEnvelope: {
            error: {
                /**
                 * @description 기계 판정용 에러코드 (SCREAMING_SNAKE_CASE). **프론트 분기의 유일한 근거다.**
                 * @example VALIDATION_FAILED
                 * @example MEMBER_NOT_FOUND
                 * @example INSUFFICIENT_POINTS
                 */
                code: string;
                /**
                 * @description 사용자에게 그대로 보여줄 수 있는 문구.
                 *     **내부 정보(스택·쿼리·경로·저장소 구조·계정 존재 여부) 노출 금지.**
                 */
                message: string;
                /**
                 * @description 400 / 422 검증 실패 시에만 채운다. 프론트가 `name` 으로 입력 필드에 매핑한다.
                 *     없으면 `null`.
                 */
                fields?: components["schemas"]["ErrorField"][] | null;
                /**
                 * @description 코드별 부가 데이터. **키 집합은 `error.code` 마다 각 엔드포인트의 에러 목록이 확정한다.**
                 *     봉투 구조 자체는 바뀌지 않는다. 없으면 `null`.
                 *     예: `INVALID_CREDENTIALS` → `{ failedCount, maxAttempts }`,
                 *     `WIDGET_FORBIDDEN` → `{ requiredKeys: string[] }`.
                 */
                details?: {
                    [key: string]: unknown;
                } | null;
                /**
                 * @description 로그 상관관계 ID. 500 문의 시 사용자가 그대로 전달한다.
                 * @example 01J8X4K2M9P7Q3R5S6T8V0W2Y4
                 */
                traceId: string;
            };
        };
        /**
         * ErrorField
         * @description 검증 실패한 필드 1건. `name` 은 요청 파라미터명 또는 헤더명이다.
         */
        ErrorField: {
            /**
             * @example email
             * @example password
             * @example amount
             * @example If-Match
             * @example Idempotency-Key
             */
            name: string;
            /**
             * @description `code` 값은 3종으로 한정한다 (BE-001 §2 · BE-002 §2).
             * @enum {string}
             */
            code: "REQUIRED" | "INVALID_FORMAT" | "OUT_OF_RANGE";
            message: string;
        };
        /**
         * UserRole
         * @description 역할. **인증 성공 응답(`session.role`)으로만 전달된다** (프론트 `UserRole` — login/api.ts).
         *     BE-003/BE-004 의 권한 모델(`admin` · `operator`)과는 **다른 어휘다** — 대조 §불일치 목록 참조.
         * @enum {string}
         */
        UserRole: "system_admin" | "operator" | "viewer";
        /**
         * AuthSession
         * @description 발급된 세션 (프론트 `AuthSession` — login/api.ts).
         *     `session.ts` 의 `isAuthSession` 이 이 4개 필드의 타입과 `role` enum 을 검사한다 —
         *     서버 응답이 이 검사를 통과해야 세션이 유효로 인정된다 (FS-001-EL-025).
         */
        AuthSession: {
            /** @description 사용자 식별자. */
            userId: string;
            /**
             * @description **정규화된**(소문자·trim) 이메일. 요청값이 아니라 **서버 정규화 결과**를 돌려준다 —
             *     서버는 신뢰 경계이므로 프론트의 `normalizeEmail` 과 동일 정규화를 재수행한다.
             */
            email: string;
            role: components["schemas"]["UserRole"];
            /**
             * Format: int64
             * @description 발급 시각. **epoch milliseconds 정수**다 (`isAuthSession` 이 `typeof === 'number'` 로 검사한다).
             */
            issuedAt: number;
        };
        /**
         * LoginInput
         * @description 프론트 `LoginInput` (login/api.ts) 과 필드가 동일하다.
         */
        LoginInput: {
            /**
             * @description 형식 `로컬부@도메인부.TLD` (공백 불가, `@` 정확히 1개, 도메인부에 `.` 1개 이상).
             *     프론트가 소문자·trim 정규화해 보내지만 **서버는 신뢰 경계이므로 동일 정규화를 재수행한 뒤 검증한다.**
             *     원천: `login/validation.ts` (`EMAIL_MAX_LENGTH = 254`).
             * @example admin@tds.local
             */
            email: string;
            /**
             * @description 구성 문자 제한 없음. **trim 하지 않는다** — 공백도 유효 문자다 (`validatePassword` 와 동일 규칙).
             *     원천: `login/validation.ts` (`PASSWORD_MIN_LENGTH = 8`, `PASSWORD_MAX_LENGTH = 64`).
             */
            password: string;
        };
        /**
         * TabId
         * @description 업무 탭 (프론트 `TabId` — dashboard/types.ts).
         * @enum {string}
         */
        TabId: "products" | "inquiries" | "sales";
        /**
         * TodoItem
         * @description 오늘의 할일 1건 (프론트 `TodoItem`). 탭당 최대 **4건**.
         */
        TodoItem: {
            key: string;
            label: string;
            /** @description 프론트는 1 이상이면 danger, 0 이면 disabled 색으로 렌더한다 (FS-002-EL-019). */
            count: number;
            /**
             * @description 클릭 시 이동할 **프론트 라우트 경로** (예: `/products/returns`).
             *     **서버가 프론트 라우팅을 아는 결합이다** — 현행 유지 결정 (BE-002 §7.2-3).
             */
            to: string;
        };
        /**
         * ListRow
         * @description 리스트 카드의 한 행 (프론트 `ListRow`).
         */
        ListRow: {
            id: string;
            /** @description 200자 상한. 초과분은 서버가 자르고 말줄임표 없이 보낸다 (무제한 길이는 레이아웃을 파괴한다). */
            title: string;
            /**
             * @description **마스킹된 값**으로 내려준다 (예: `테스***`). **원문 성명을 응답에 담지 않는다** —
             *     마스킹은 서버가 수행한다 (FS-002-EL-024 비고).
             */
            actor: string;
            /**
             * Format: date
             * @description `YYYY-MM-DD`
             */
            date: string;
        };
        /**
         * ListCardData
         * @description 리스트 카드 1장 (프론트 `ListCardData`).
         */
        ListCardData: {
            /** @description 탭별 고정값 (BE-002 §4 카드 고정값 표). */
            title: string;
            /**
             * @description **`rows` 를 상한으로 자르기 전의 전체 건수**다 — `rows.length` 와 일치하지 않을 수 있다.
             *     0 이하이면 프론트가 뱃지를 숨긴다. 자릿수 상한 없음.
             */
            count: number;
            /** @description '더보기' 이동 경로 (프론트 라우트). */
            moreTo: string;
            /** @enum {string} */
            icon: "order" | "tag" | "question" | "contract";
            /**
             * @description **카드당 5행 상한.** 서버가 `date` 내림차순(최신 우선)으로 정렬해 5행까지 자른다.
             *     프론트에 페이징·가상화가 없다 — 서버가 상한을 지켜야 한다.
             */
            rows: components["schemas"]["ListRow"][];
        };
        /**
         * TabData
         * @description 탭 하나에 대응하는 대시보드 데이터 (프론트 `TabData`).
         */
        TabData: {
            /** @description 오늘의 할일. `dashboard.todo` 권한이 OFF 면 **빈 배열로 소거**한다 (서버가 수행한다). */
            todos: components["schemas"]["TodoItem"][];
            /**
             * @description **정확히 2장.** 프론트 타입이 튜플 `readonly [ListCardData, ListCardData]` 이므로
             *     1장·3장은 계약 위반이다. OpenAPI 3.1 은 JSON Schema 2020-12 이므로 `prefixItems` 로
             *     **고정 길이 튜플**을 표현한다 (`minItems`/`maxItems` 만으로는 타입 생성기가 튜플을 만들지 못한다).
             *     `dashboard.lists` 권한이 OFF 면 `rows: []` · `count: 0` 으로 소거하되
             *     `title` · `moreTo` · `icon`(탭별 고정 라벨)과 **2장 튜플은 유지한다** — 타입 계약이다.
             */
            cards: [
                components["schemas"]["ListCardData"],
                components["schemas"]["ListCardData"]
            ];
        };
        /**
         * StatsRange
         * @description 통계 조회 기간 (프론트 `StatsRange` — dashboard/stats-types.ts).
         * @enum {string}
         */
        StatsRange: "day" | "week" | "month";
        /**
         * VisitorPoint
         * @description 방문자 차트의 한 점 (프론트 `VisitorPoint`).
         */
        VisitorPoint: {
            /**
             * @description **x축 라벨 문자열을 서버가 만든다.** 형식이 `range` 에 종속된다 —
             *     `day`: `7.14` / `week`: `7월 2주` / `month`: `7월` (FS-002-EL-033).
             *     프론트는 이 값을 그대로 렌더한다 (포맷팅하지 않는다).
             */
            label: string;
            visitors: number;
            pageViews: number;
        };
        /**
         * PeriodRow
         * @description 기간별 분석 표의 일자 행 (프론트 `PeriodRow`).
         */
        PeriodRow: {
            /**
             * Format: date
             * @description `YYYY-MM-DD`. **최신 날짜가 배열 앞**에 오도록 서버가 내림차순 정렬한다.
             */
            date: string;
            orders: number;
            /**
             * @description **원 단위 정수.** 프론트가 ko-KR 천 단위 구분 기호와 '원'을 붙인다 —
             *     **서버는 숫자만 보낸다** (문자열·통화 기호 금지).
             */
            revenue: number;
            visitors: number;
            signups: number;
            inquiries: number;
            reviews: number;
        };
        /**
         * PeriodSummary
         * @description 합계 행 (프론트 `PeriodSummary`) — `date` 대신 `label` 을 갖는다.
         */
        PeriodSummary: {
            /** @description **2건 고정**: `최근 7일 합계` · `이번달 합계` (FS-002-EL-038). */
            label: string;
            orders: number;
            revenue: number;
            visitors: number;
            signups: number;
            inquiries: number;
            reviews: number;
        };
        /**
         * StatsData
         * @description 통계 응답 (프론트 `StatsData`).
         */
        StatsData: {
            /**
             * @description 방문자 계열. 점 수는 기간별 고정: `day` **7개** · `week` **4개** · `month` **5개**.
             *     프론트 x축은 점 수로 균등 분할하며 솎아내기 규칙이 없다 — 서버가 상한을 지켜야 한다.
             *     `dashboard.stats.visitors` 권한이 OFF 면 **빈 배열로 소거**한다.
             */
            visitors: components["schemas"]["VisitorPoint"][];
            /**
             * @description **7행 고정.** `range` 값과 무관하다 (현재 구현에서 기간에 따라 달라지지 않는다).
             *     `dashboard.stats.period` 권한이 OFF 면 `summaries` 와 함께 **빈 배열로 소거**한다.
             */
            periodRows: components["schemas"]["PeriodRow"][];
            /** @description **2행 고정** (FS-002-EL-038). */
            summaries: components["schemas"]["PeriodSummary"][];
        };
        /**
         * MemberTier
         * @description 회원 등급 (프론트 `MemberTier` — shared/domain/member.ts).
         *     고객은 **회원가입으로만 유입된다** — 관리자가 회원을 만드는 API 는 이 계약에 존재하지 않는다.
         * @enum {string}
         */
        MemberTier: "normal" | "vip" | "vvip";
        /**
         * MemberTierFilter
         * @description 등급 필터 값 — `MemberTier` + `all` (프론트 `MemberQuery.tier`).
         * @default all
         * @enum {string}
         */
        MemberTierFilter: "all" | "normal" | "vip" | "vvip";
        /**
         * MemberActivity
         * @description 글/댓글/구매평/문의 활동 카운트 (프론트 `MemberActivity`).
         */
        MemberActivity: {
            posts: number;
            comments: number;
            reviews: number;
            inquiries: number;
        };
        /**
         * MemberGroup
         * @description 회원 그룹 (프론트 `MemberGroup`). 프론트가 쓰는 필드는 `id` · `label` 뿐이다.
         */
        MemberGroup: {
            /** @description `GET /members` 의 `groupId` 쿼리와 `groupCounts` 의 키로 그대로 쓰인다. */
            id: string;
            /** @description 그룹 표시명. 좌측 필터 항목 라벨과 `Member.group` 이 같은 값을 쓴다. */
            label: string;
        };
        /**
         * Member
         * @description 회원 목록의 1건 (프론트 `Member` — shared/domain/member.ts).
         */
        Member: {
            /** @example M-00001 */
            id: string;
            nickname: string;
            account: string;
            tier: components["schemas"]["MemberTier"];
            /** @description 그룹 id — 필터가 이 값으로 건다. */
            groupId: string;
            /** @description 그룹 표시명 — 표/CSV 가 그대로 쓴다. */
            group: string;
            /**
             * Format: date
             * @description `YYYY-MM-DD`
             */
            joinedAt: string;
            /**
             * Format: date-time
             * @description 오프셋을 포함한 ISO 8601 date-time. **상대 시각 계산('4시간전')에 시·분이 필요하다**
             *     (FS-003-EL-011.7).
             */
            joinedAtIso: string;
            points: number;
            activity: components["schemas"]["MemberActivity"];
            totalPurchase: number;
            /** @description 목록에서는 hover title 로만 쓰인다 (FS-003-EL-011.11). 없으면 빈 문자열. */
            memo: string;
        };
        /**
         * TierCounts
         * @description 등급별 **전체** 건수 (프론트 `TierCounts`).
         *     **검색·그룹 필터와 무관하게 삭제되지 않은 전체 회원 기준이다** —
         *     좌측 필터 배지가 검색할 때마다 흔들리면 안 된다 (FS-003-EL-003 비고).
         */
        TierCounts: {
            all: number;
            normal: number;
            vip: number;
            vvip: number;
        };
        /**
         * GroupCounts
         * @description 그룹별 **전체** 건수 (프론트 `GroupCounts` = `Record<string, number>`, 키 = 그룹 id).
         *     **검색·등급 필터와 무관하게 전체 회원 기준이다.**
         *     `GET /member-groups` 가 돌려주는 **모든 그룹 id 를 키로 포함하며, 회원이 0명인 그룹도 `0` 으로 채운다.**
         * @example {
         *       "none": 492,
         *       "free-shipping": 5
         *     }
         */
        GroupCounts: {
            [key: string]: number;
        };
        /**
         * MemberListResult
         * @description 회원 목록 응답 (프론트 `MemberListResult` — members/types.ts).
         */
        MemberListResult: {
            /** @description 현재 페이지의 회원. */
            members: components["schemas"]["Member"][];
            counts: components["schemas"]["TierCounts"];
            groupCounts: components["schemas"]["GroupCounts"];
            /**
             * @description 필터·검색을 **적용한 뒤**의 전체 건수. 페이지네이션과 조회 요약이 쓴다.
             *     `page` 가 총 페이지 수를 넘어도 이 값은 조건에 걸린 실제 건수다 (서버는 페이지를 보정하지 않는다).
             */
            total: number;
        };
        /**
         * GroupType
         * @description 그룹 유형 (프론트 `GroupType` — members/types.ts).
         *     `POST /member-groups` 는 `staff` 를 **받는다** (프론트가 보낼 수 있는 값을 서버가 거절하면
         *     화면에 도달 불가능한 선택지가 남는다). 그러나 `GET /member-groups` 는 `member` 만 반환한다 (BE-003 §7.4).
         * @enum {string}
         */
        GroupType: "member" | "staff";
        /**
         * ShippingBenefit
         * @description 배송비 혜택 (프론트 `ShippingBenefit`). 그룹에 저장되어 **주문 도메인이 소비한다** —
         *     `MemberGroup` 응답 스키마에는 노출하지 않는다 (프론트가 쓰지 않는다).
         * @enum {string}
         */
        ShippingBenefit: "none" | "free" | "conditional";
        /**
         * CreateGroupInput
         * @description 그룹 생성 요청 (프론트 `CreateGroupInput`).
         */
        CreateGroupInput: {
            /** @description 앞뒤 공백 제거 후 1–30자 (FS-003-EL-016.3). **제어문자 금지.** */
            name: string;
            type: components["schemas"]["GroupType"];
            shippingBenefit: components["schemas"]["ShippingBenefit"];
        };
        /**
         * ConsentItem
         * @description 동의 항목 1건 (프론트 `ConsentItem`) — 비활성 체크박스(읽기 전용)로 표시된다.
         */
        ConsentItem: {
            id: string;
            label: string;
            agreed: boolean;
            /**
             * @description **`YYYY-MM-DD HH:mm` 형식 문자열**이며 미동의면 `null` (FS-004-EL-005.5).
             * @example 2026-03-02 09:14
             */
            agreedAt: string | null;
        };
        /**
         * ConsentGroup
         * @description 동의 묶음 (프론트 `ConsentGroup`).
         *     **그룹 구성은 서버가 결정한다** — 프론트에 하드코딩된 목록이 없다.
         */
        ConsentGroup: {
            id: string;
            label: string;
            items: components["schemas"]["ConsentItem"][];
        };
        /**
         * PointEntry
         * @description 적립금 증감 내역 1행 (프론트 `PointEntry`).
         */
        PointEntry: {
            /** @example PE-00042-003 */
            id: string;
            /**
             * Format: date
             * @description `YYYY-MM-DD` (서버 시각 기준).
             */
            date: string;
            reason: string;
            /**
             * @description 관련 주문번호. **수기 지급/차감이면 `null`** 이며, 프론트가 `'—'` 로 표시한다.
             *     **`orderNo` 가 `null` 인 내역만 취소할 수 있다** (BE-004 §7.2).
             */
            orderNo: string | null;
            /** @description **부호 포함** — 양수 = 지급, 음수 = 차감. **프론트가 부호를 만들지 않는다.** */
            amount: number;
        };
        /**
         * Coupon
         * @description 보유 쿠폰 1건 (프론트 `Coupon`).
         */
        Coupon: {
            id: string;
            name: string;
            benefit: string;
            /**
             * Format: date
             * @description `YYYY-MM-DD`
             */
            expiresAt: string;
        };
        /**
         * MemberDetail
         * @description 회원 상세 (프론트 `MemberDetail` — shared/domain/member.ts).
         *     **회원 정보는 전부 읽기 전용이다** — 관리자가 바꿀 수 있는 값은 비밀번호뿐이다 (FS-004 §1.1).
         *     **`password` 는 응답에 포함하지 않는다.**
         */
        MemberDetail: {
            id: string;
            nickname: string;
            referralCode: string;
            tier: components["schemas"]["MemberTier"];
            account: string;
            name: string;
            phone: string;
            country: string;
            address: string;
            addressDetail: string;
            /**
             * @description `YYYY-MM-DD`. **비어 있는 값은 빈 문자열로 내려준다** — 회원 정보 필드에 `null` 을 쓰지 않는다.
             *     프론트가 `'—'` 대체를 직접 판단한다.
             */
            birthday: string;
            /** @description '카카오' / '네이버' / '없음' 등. 비어 있으면 빈 문자열. */
            socialLogin: string;
            /** @description 추천인 닉네임 — 없으면 빈 문자열. */
            referrer: string;
            consents: components["schemas"]["ConsentGroup"][];
            /** Format: date-time */
            joinedAtIso: string;
            /** Format: date-time */
            lastLoginAtIso: string;
            loginCount: number;
            lastLoginIp: string;
            activity: components["schemas"]["MemberActivity"];
            /**
             * @description 보유 적립금 잔액. **전체 이력의 합이며 `pointHistory` 의 최근 3개월 범위에 갇히지 않는다** —
             *     표에 보이지 않는 오래된 내역도 잔액에 포함된다.
             */
            points: number;
            /**
             * @description **최근 3개월(90일)** 로 서버가 범위를 제한한다. **최신 내역이 배열 앞**이다.
             *     **취소된 내역과 그 상쇄 거래는 이 배열에서 제외한다** (BE-004 §7.2).
             */
            pointHistory: components["schemas"]["PointEntry"][];
            /** @description 전량 반환한다 (페이징 없음). */
            coupons: components["schemas"]["Coupon"][];
            /** @description 관리자 메모. 없으면 빈 문자열. */
            memo: string;
        };
        /**
         * ChangePasswordInput
         * @description 비밀번호 변경 요청. 어댑터 `changePassword(id, password)` 가 값 하나만 받는다 —
         *     '새 비밀번호 확인'은 프론트 전용 검증이며 서버로 전송되지 않는다.
         */
        ChangePasswordInput: {
            /**
             * @description 8–64자. **영문 1자 이상 + 숫자 1자 이상 포함** (FS-004-EL-013.4).
             *     공백만으로 이뤄질 수 없다. 특수문자는 요구하지 않는다.
             *     상한 64자는 BE-004 가 확정한 값이다 (프론트에 길이 상한이 없다 — FS-004 §7 #8).
             */
            password: string;
        };
        /**
         * PointAdjustKind
         * @description 적립금 조정 종류 (프론트 `PointAdjustKind`). 부호는 이 값이 결정한다.
         * @enum {string}
         */
        PointAdjustKind: "grant" | "deduct";
        /**
         * PointAdjustInput
         * @description 적립금 지급/차감 요청 (프론트 `PointAdjustInput`).
         */
        PointAdjustInput: {
            kind: components["schemas"]["PointAdjustKind"];
            /**
             * @description **부호 없는 절댓값**이다 — 부호는 `kind` 가 결정한다 (FS-004-EL-007.3).
             *     상한 1,000,000 은 BE-004 가 확정한 값이다 (프론트에 상한이 없다 — FS-004 §7 #8).
             */
            amount: number;
            /** @description 앞뒤 공백 제거 후 1–100자 (FS-004-EL-007.4). **제어문자 금지.** */
            reason: string;
        };
        /**
         * SaveMemoInput
         * @description 관리자 메모 저장 요청.
         */
        SaveMemoInput: {
            /**
             * @description 0–500자 (프론트 `MEMO_MAX_LENGTH = 500`).
             *     **빈 문자열을 허용한다** — 메모를 비워서 저장할 수 있다 (FS-004-EL-009.3).
             *     **앞뒤 공백을 제거하지 않는다.**
             */
            memo: string;
        };
    };
    responses: {
        /**
         * @description 400 `VALIDATION_FAILED` — 요청 파라미터·헤더가 제약을 위반했다.
         *     `error.fields[]` 에 `{ name, code, message }` 를 채운다. `name` 은 요청 파라미터명 또는 헤더명이다.
         */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description 401 `UNAUTHENTICATED` — 유효한 세션 자격 증명 없음·만료.
         *     프론트 기대 동작은 `/login?returnUrl=<현재경로>&reason=session_expired` 이동이지만
         *     **현재 프론트에 401 처리 경로가 없다** (BE-002 §7.2-1 · BE-003 §7.7 #3 · BE-004 §7.6 #8 —
         *     UI 기획 · 프론트 구현 변경 요청).
         */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description 403 `FORBIDDEN` — 인증됐으나 역할이 부족하다.
         *     **컬렉션 리소스의 존재는 비밀이 아니므로 은닉하지 않는다** (BE-003 §3.2 원칙 1).
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description - `FORBIDDEN` — 쓰기 권한 부족 (`operator` 등). **읽기 권한이 있는 주체에게는 은닉하지 않는다** —
         *       이미 회원의 존재를 아는 주체에게 존재를 숨기는 것은 의미가 없고, 정당한 운영자가 권한 문제를
         *       인지하지 못하게 만든다 (BE-003 §3.2 원칙 2).
         *     - `CSRF_TOKEN_INVALID` — `X-CSRF-Token` 누락·불일치.
         */
        ForbiddenOrCsrf: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description 404 `MEMBER_NOT_FOUND` — **없는 id · 삭제(탈퇴)된 회원 · 회원 도메인 읽기 권한 없음(은닉)** 을
         *     **구분하지 않는다** (BE-003 §3.2 · BE-004 §3.2). 개별 회원 리소스의 **존재 자체가 개인정보**이며,
         *     구분하면 삭제 이력과 id 존재가 노출된다.
         *     어댑터는 이 코드를 `new Error('회원을 찾을 수 없습니다')` 로 변환한다 —
         *     **이 문자열은 계약의 일부다** (`MemberDetailPage.tsx` 가 이 메시지로 FS-004-EL-012 를 분기한다).
         */
        MemberNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 429 `RATE_LIMITED` — 레이트리밋 초과. `Retry-After` 헤더(초)를 함께 반환한다. */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description 500 `INTERNAL_ERROR` — 서버 내부 오류. `traceId` 필수.
         *     **내부 정보(스택·쿼리·경로·저장소 구조·계정 존재 여부)를 문구에 담지 않는다.**
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 504 `REQUEST_TIMEOUT` — 서버 처리 상한 초과. 500 과 동일한 일반 문구 + `traceId`. */
        RequestTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 504 `UPSTREAM_TIMEOUT` — 서버 처리 상한(3초) 초과 (BE-002 §4.2). */
        UpstreamTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description 회원 id (예: `M-00042`). */
        MemberId: string;
        /**
         * @description 세션 쿠키 기반 인증이므로 상태 변경 요청(POST · PUT · PATCH · DELETE)은 이 헤더를 요구한다.
         *     누락·불일치 시 403 `CSRF_TOKEN_INVALID` (BE-003 §3.3 · BE-004 §3.3).
         *     **프론트 어댑터의 함수 시그니처는 바뀌지 않는다** — 함수 본문이 헤더를 싣는다.
         */
        CsrfToken: string;
        /** @description 등급 필터. `all` 은 등급 조건 없음. `groupId` 와 **AND** 로 결합한다. */
        TierQuery: components["schemas"]["MemberTierFilter"];
        /** @description 그룹 필터. `all` 은 그룹 조건 없음 (프론트 상수 `GROUP_ALL`). */
        GroupIdQuery: string;
        /**
         * @description 닉네임 **또는** 계정에 대한 대소문자 무시 부분 일치. 서버가 앞뒤 공백을 제거한다.
         *     빈 문자열이면 조건 없음. **50자를 넘으면 400** — 프론트에는 길이 제약이 없다 (BE-003 §7.7 #9).
         */
        KeywordQuery: string;
    };
    requestBodies: never;
    headers: {
        /** @description 재시도까지 남은 시간(초). */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description 인증 성공 — 세션 발급 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session: components["schemas"]["AuthSession"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            /**
             * @description `INVALID_CREDENTIALS` — 비밀번호 불일치 **또는** 미등록 이메일 **또는** 비활성 계정의 비밀번호 불일치.
             *     세 경우가 동일한 응답이다 (BE-001 §3.2). `details = { failedCount, maxAttempts: 5 }`.
             *     **`UNAUTHENTICATED` 는 이 엔드포인트에서 발생하지 않는다** (BE-001 §3.3).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description `ACCOUNT_INACTIVE` — 비밀번호가 **일치**하고 계정이 비활성일 때만 반환한다.
             *     비밀번호를 아는 시점에 계정 존재는 이미 알려진 정보이므로 증분 노출이 없다 (BE-001 §3.2).
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description `ACCOUNT_LOCKED` — 연속 실패 5회 도달 또는 잠금(30분) 유지 중.
             *     **미등록 이메일도 동일 임계값에서 잠긴다** (BE-001 §4 잠금 규칙 3 — 계정 열거 오라클 차단).
             *     잔여 초는 `Retry-After` 헤더. 잠금 해제 시각을 바디에 넣지 않는다 (잠금 규칙 7).
             */
            423: {
                headers: {
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            /** @description `AUTH_TIMEOUT` — 서버 인증 처리가 5초 상한을 초과했다. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getDashboardTab: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 활성 업무 탭. 열거값 밖이면 400 (404 가 아니다). */
                tab: components["schemas"]["TabId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 탭 데이터 (프론트 `TabData`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TabData"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            /**
             * @description `TAB_FORBIDDEN` (탭 권한 없음) 또는 `WIDGET_FORBIDDEN` (할일·리스트 권한이 둘 다 없음).
             *     `details.requiredKeys` 에 필요한 권한 키를 담는다.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["UpstreamTimeout"];
        };
    };
    getDashboardStats: {
        parameters: {
            query: {
                /** @description 조회 기간. 프론트 기본값은 `day` (`DEFAULT_STATS_RANGE`). */
                range: components["schemas"]["StatsRange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 통계 데이터 (프론트 `StatsData`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsData"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            /** @description `WIDGET_FORBIDDEN` — 방문자·기간별 분석 권한이 둘 다 없다. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["UpstreamTimeout"];
        };
    };
    listMembers: {
        parameters: {
            query?: {
                /** @description 등급 필터. `all` 은 등급 조건 없음. `groupId` 와 **AND** 로 결합한다. */
                tier?: components["parameters"]["TierQuery"];
                /** @description 그룹 필터. `all` 은 그룹 조건 없음 (프론트 상수 `GROUP_ALL`). */
                groupId?: components["parameters"]["GroupIdQuery"];
                /**
                 * @description 닉네임 **또는** 계정에 대한 대소문자 무시 부분 일치. 서버가 앞뒤 공백을 제거한다.
                 *     빈 문자열이면 조건 없음. **50자를 넘으면 400** — 프론트에는 길이 제약이 없다 (BE-003 §7.7 #9).
                 */
                keyword?: components["parameters"]["KeywordQuery"];
                /** @description 페이지 번호 (1-base). */
                page?: number;
                /** @description 페이지 크기. 프론트는 `PAGE_SIZE`(10)를 싣는다. */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회원 목록 (프론트 `MemberListResult`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResult"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["RequestTimeout"];
        };
    };
    exportMembers: {
        parameters: {
            query?: {
                /** @description 등급 필터. `all` 은 등급 조건 없음. `groupId` 와 **AND** 로 결합한다. */
                tier?: components["parameters"]["TierQuery"];
                /** @description 그룹 필터. `all` 은 그룹 조건 없음 (프론트 상수 `GROUP_ALL`). */
                groupId?: components["parameters"]["GroupIdQuery"];
                /**
                 * @description 닉네임 **또는** 계정에 대한 대소문자 무시 부분 일치. 서버가 앞뒤 공백을 제거한다.
                 *     빈 문자열이면 조건 없음. **50자를 넘으면 400** — 프론트에는 길이 제약이 없다 (BE-003 §7.7 #9).
                 */
                keyword?: components["parameters"]["KeywordQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조건에 걸린 회원 전량. 0건이면 빈 배열 (프론트가 헤더 행만 든 CSV 를 내려받는다). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /**
             * @description `EXPORT_TOO_LARGE` — 조건에 걸린 회원이 50,000명을 넘는다.
             *     message = '조건에 걸린 회원이 50,000명을 넘습니다. 등급·그룹·검색어로 범위를 좁혀 주세요.'
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["RequestTimeout"];
        };
    };
    listMemberGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회원 그룹 전량 (프론트 `MemberGroup[]`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberGroup"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["RequestTimeout"];
        };
    };
    createMemberGroup: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 쿠키 기반 인증이므로 상태 변경 요청(POST · PUT · PATCH · DELETE)은 이 헤더를 요구한다.
                 *     누락·불일치 시 403 `CSRF_TOKEN_INVALID` (BE-003 §3.3 · BE-004 §3.3).
                 *     **프론트 어댑터의 함수 시그니처는 바뀌지 않는다** — 함수 본문이 헤더를 싣는다.
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupInput"];
            };
        };
        responses: {
            /**
             * @description 생성된 그룹. `label` 은 앞뒤 공백을 제거한 `name` 이다.
             *     프론트 `createGroup(...): Promise<void>` 는 **본문을 사용하지 않고** 성공 후 그룹 목록을 재조회한다 —
             *     본문은 다른 소비자를 위한 표준 반환이며 프론트 계약을 바꾸지 않는다.
             */
            201: {
                headers: {
                    /** @description 생성된 그룹의 경로 (`/api/member-groups/<id>`) */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberGroup"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrCsrf"];
            /**
             * @description `GROUP_NAME_DUPLICATED` — 같은 `type` 안에 정규화한 이름이 이미 있다 (BE-003 §7.3).
             *     재시도해도 같은 결과다 — 프론트 문구 분기는 UI 기획 쪽 변경 요청 (BE-003 §7.7 #5).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description `GROUP_LIMIT_EXCEEDED` — 그룹 수가 상한 200개에 도달했다 (BE-003 §7.5). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["RequestTimeout"];
        };
    };
    getMemberDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회원 상세 (프론트 `MemberDetail`) */
            200: {
                headers: {
                    /** @description **메모 버전만** 반영하는 불투명 문자열. `PUT /members/{id}/memo` 의 `If-Match` 에 그대로 싣는다. */
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDetail"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["MemberNotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["RequestTimeout"];
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 쿠키 기반 인증이므로 상태 변경 요청(POST · PUT · PATCH · DELETE)은 이 헤더를 요구한다.
                 *     누락·불일치 시 403 `CSRF_TOKEN_INVALID` (BE-003 §3.3 · BE-004 §3.3).
                 *     **프론트 어댑터의 함수 시그니처는 바뀌지 않는다** — 함수 본문이 헤더를 싣는다.
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 (본문 없음). 이미 삭제된 회원에 대한 재요청도 204 다 (멱등). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrCsrf"];
            404: components["responses"]["MemberNotFound"];
            /**
             * @description `MEMBER_HAS_OPEN_ORDERS` — 결제 대기·배송 중 주문이 남아 있다.
             *     message = '진행 중인 주문이 있어 삭제할 수 없습니다.' (수취인이 사라지면 배송·환불 경로가 끊긴다)
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["RequestTimeout"];
        };
    };
    changeMemberPassword: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 쿠키 기반 인증이므로 상태 변경 요청(POST · PUT · PATCH · DELETE)은 이 헤더를 요구한다.
                 *     누락·불일치 시 403 `CSRF_TOKEN_INVALID` (BE-003 §3.3 · BE-004 §3.3).
                 *     **프론트 어댑터의 함수 시그니처는 바뀌지 않는다** — 함수 본문이 헤더를 싣는다.
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInput"];
            };
        };
        responses: {
            /** @description 변경됨 (본문 없음) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrCsrf"];
            404: components["responses"]["MemberNotFound"];
            /**
             * @description `SOCIAL_ONLY_ACCOUNT` — 비밀번호가 없는 소셜 로그인 전용 계정이다.
             *     message = '소셜 로그인 전용 계정은 비밀번호를 설정할 수 없습니다.'
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["RequestTimeout"];
        };
    };
    addPointEntry: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 쿠키 기반 인증이므로 상태 변경 요청(POST · PUT · PATCH · DELETE)은 이 헤더를 요구한다.
                 *     누락·불일치 시 403 `CSRF_TOKEN_INVALID` (BE-003 §3.3 · BE-004 §3.3).
                 *     **프론트 어댑터의 함수 시그니처는 바뀌지 않는다** — 함수 본문이 헤더를 싣는다.
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /**
                 * @description UUID v4. **필수다.** 같은 키 + 같은 바디는 최초 응답을 재생한다 (보존 24시간).
                 *     누락하면 400 `VALIDATION_FAILED` (`error.fields[].name = "Idempotency-Key"`).
                 */
                "Idempotency-Key": string;
            };
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointAdjustInput"];
            };
        };
        responses: {
            /**
             * @description 생성된 내역 1행. `amount` 는 **부호 포함**(`grant` 양수 · `deduct` 음수) —
             *     **프론트가 부호를 만들지 않는다**. `orderNo` 는 수기 조정이므로 항상 `null` 이다.
             *     같은 `Idempotency-Key` + 같은 바디의 재요청은 이 응답을 그대로 재생한다.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointEntry"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrCsrf"];
            404: components["responses"]["MemberNotFound"];
            /** @description `IDEMPOTENCY_CONFLICT` — 같은 `Idempotency-Key` 로 **다른 바디**를 보냈다. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description - `INSUFFICIENT_POINTS` — `kind=deduct` 이고 `amount` > 서버 잔액.
             *       message = '보유 적립금보다 많이 차감할 수 없습니다.'
             *     - `BALANCE_LIMIT_EXCEEDED` — `kind=grant` 이고 지급 후 잔액이 100,000,000 을 넘는다.
             *       message = '적립금 잔액 상한을 넘습니다.'
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            /**
             * @description `REQUEST_TIMEOUT` — 서버 처리 5초 초과. **504 를 받아도 처리가 완료됐을 수 있다** —
             *     같은 `Idempotency-Key` 로 재시도하면 중복 없이 결과를 확인할 수 있다.
             */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    removePointEntry: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 쿠키 기반 인증이므로 상태 변경 요청(POST · PUT · PATCH · DELETE)은 이 헤더를 요구한다.
                 *     누락·불일치 시 403 `CSRF_TOKEN_INVALID` (BE-003 §3.3 · BE-004 §3.3).
                 *     **프론트 어댑터의 함수 시그니처는 바뀌지 않는다** — 함수 본문이 헤더를 싣는다.
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
                /** @description 적립금 내역 id (`PointEntry.id`). **이 회원의 내역이 아니면 404** (내역 id 열거 차단). */
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 취소됨 (본문 없음). 이미 취소된 내역의 재요청도 204 이며 잔액을 다시 되돌리지 않는다. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrCsrf"];
            /**
             * @description - `MEMBER_NOT_FOUND` — 없는 회원 id · 삭제(탈퇴)된 회원 · 권한 은닉
             *     - `POINT_ENTRY_NOT_FOUND` — `entryId` 가 없거나 **이 회원의 내역이 아니다** (내역 id 열거 차단)
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description - `POINT_ENTRY_NOT_REVERSIBLE` — 주문 연동 적립(`orderNo !== null`)이다.
             *       message = '주문에 연동된 적립 내역은 취소할 수 없습니다.'
             *     - `INSUFFICIENT_POINTS` — 취소하면 잔액이 음수가 된다.
             *       message = '이미 사용된 적립금이라 취소할 수 없습니다.'
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["RequestTimeout"];
        };
    };
    saveMemberMemo: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 쿠키 기반 인증이므로 상태 변경 요청(POST · PUT · PATCH · DELETE)은 이 헤더를 요구한다.
                 *     누락·불일치 시 403 `CSRF_TOKEN_INVALID` (BE-003 §3.3 · BE-004 §3.3).
                 *     **프론트 어댑터의 함수 시그니처는 바뀌지 않는다** — 함수 본문이 헤더를 싣는다.
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /**
                 * @description `GET /members/{id}` 가 내려준 `ETag`(메모 버전). **필수다.**
                 *     누락하면 400 (`error.fields[].name = "If-Match"`). 불일치하면 409 `MEMO_CONFLICT`.
                 */
                "If-Match": string;
            };
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveMemoInput"];
            };
        };
        responses: {
            /**
             * @description 저장됨 (본문 없음). **새 `ETag` 를 응답 헤더로 반환한다** —
             *     어댑터가 보관해 다음 저장의 `If-Match` 로 쓴다 (BE-004 §6.1 #4).
             */
            204: {
                headers: {
                    /** @description 저장 후의 새 메모 버전. */
                    ETag: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            /** @description `CSRF_TOKEN_INVALID` — `X-CSRF-Token` 누락·불일치. (`FORBIDDEN` 은 발생하지 않는다) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: components["responses"]["MemberNotFound"];
            /**
             * @description `MEMO_CONFLICT` — `If-Match` 가 서버의 현재 메모 버전과 다르다 (**다른 관리자가 먼저 저장했다**).
             *     message = '다른 관리자가 메모를 먼저 저장했습니다. 새로고침 후 다시 시도해 주세요.'
             *     재시도해도 같은 409 가 반복된다 — 프론트 문구 분기는 UI 기획 쪽 변경 요청 (BE-004 §7.6 #6).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["RequestTimeout"];
        };
    };
    sendMemberNotification: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 세션 쿠키 기반 인증이므로 상태 변경 요청(POST · PUT · PATCH · DELETE)은 이 헤더를 요구한다.
                 *     누락·불일치 시 403 `CSRF_TOKEN_INVALID` (BE-003 §3.3 · BE-004 §3.3).
                 *     **프론트 어댑터의 함수 시그니처는 바뀌지 않는다** — 함수 본문이 헤더를 싣는다.
                 */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /** @description UUID v4. 생략하면 60초 중복 흡수 창이 적용된다. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description 회원 id (예: `M-00042`). */
                id: components["parameters"]["MemberId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description **접수됨** (본문 없음). 발송 자체를 보장하지 않는다 — 큐가 발송한다.
             *     60초 창 안의 중복 요청은 최초 요청의 202 를 재생한다.
             */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["ForbiddenOrCsrf"];
            404: components["responses"]["MemberNotFound"];
            /**
             * @description `NOTIFICATION_OPT_OUT` — 회원이 **E-Mail 수신에 동의하지 않았다** (FS-004-EL-005.2).
             *     message = '이 회원은 E-Mail 수신에 동의하지 않았습니다.'
             *     채널·내용을 고를 수 없는 발송이므로 서버가 수신 동의를 강제하지 않으면 미동의 회원에게 발송된다.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            /** @description `INTERNAL_ERROR` — **큐 적재 실패를 포함한** 내부 오류. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /**
             * @description `REQUEST_TIMEOUT` — 서버 처리 5초 초과.
             *     **발송은 큐에서 계속 진행된다 — 504 를 받아도 발송이 취소되지 않는다.**
             */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
