/**
 * packages/ui 용 아이콘 기하 모듈 생성 — 정본은 앱·DS 의 실제 아이콘 구현이다.
 *
 * 계약의 name enum 이 늘면 packages/ui 의 Icon 구현도 같은 값 집합을 그려야 한다
 * (Record<IconName, …> 라 한쪽만 늘면 타입이 깨진다 — 그게 이 모듈이 존재하는 이유다).
 * 손으로 옮겨 적는 대신 추출기가 만든 기하를 그대로 내보낸다.
 *
 * [왜 마크업 문자열이 아니라 구조체인가]
 * 문자열을 dangerouslySetInnerHTML 로 꽂으면 더 이상 React 노드가 아니라서 테스트·a11y 검사가
 * 안을 볼 수 없고, 신뢰 경계도 흐려진다. 태그와 속성으로 쪼개 두면 Icon 이 진짜 React
 * 엘리먼트로 렌더할 수 있고 기존 렌더 결과와 1:1 로 대조할 수 있다.
 */
import path from 'node:path';
import { extractAllIcons } from './extract-icons';
import { REPO_ROOT, UI_GENERATED_DIR } from './paths';
import type { GeneratedFile } from './shared';

/** SVG 도형 하나 — 태그명 + 속성 맵 */
export interface ParsedShape {
  tag: string;
  attrs: Record<string, string>;
}

const SHAPE_TAGS = ['path', 'rect', 'circle', 'line', 'polyline', 'polygon', 'ellipse'];

/** `<svg …>` 안쪽의 도형들을 태그·속성으로 분해한다 (그리는 순서 보존) */
export function parseShapes(svg: string): ParsedShape[] {
  const out: ParsedShape[] = [];
  const tagRe = new RegExp(`<(${SHAPE_TAGS.join('|')})\\b([^>]*?)/?>`, 'g');
  let match: RegExpExecArray | null;
  while ((match = tagRe.exec(svg)) !== null) {
    const tag = match[1];
    const rawAttrs = match[2] ?? '';
    if (tag === undefined) continue;
    const attrs: Record<string, string> = {};
    const attrRe = /([a-zA-Z-]+)\s*=\s*"([^"]*)"/g;
    let attr: RegExpExecArray | null;
    while ((attr = attrRe.exec(rawAttrs)) !== null) {
      const key = attr[1];
      const value = attr[2];
      if (key !== undefined && value !== undefined) attrs[key] = value;
    }
    out.push({ tag, attrs });
  }
  return out;
}

export function generateIconPaths(): GeneratedFile {
  const icons = extractAllIcons(REPO_ROOT);

  const entries = icons
    .map((icon) => {
      const shapes = parseShapes(icon.svg)
        .map((shape) => `    { tag: '${shape.tag}', attrs: ${JSON.stringify(shape.attrs)} },`)
        .join('\n');
      return `  ${JSON.stringify(icon.name)}: [\n${shapes}\n  ],`;
    })
    .join('\n');

  const body = `// AUTO-GENERATED by tools/codegen (pnpm codegen) — DO NOT EDIT.
//
// 아이콘 ${String(icons.length)}종의 24 그리드 stroke 기하.
// 원천: packages/ui/src/atoms/Icon/Icon.tsx 와 apps/admin/src/**/icons.tsx 의 실제 구현을
// tools/codegen/src/extract-icons.ts 가 추출한 것. 계약(contracts/Icon.contract.json)의
// name enum 과 키가 1:1 로 일치하며, 어긋나면 codegen:check 와 커버리지 게이트가 막는다.
import type { IconName } from '../types/Icon.types';

/** SVG 도형 하나 — 태그명과 기하 속성. stroke/fill 은 <svg> 루트가 정하므로 여기엔 없다. */
export interface IconShape {
  readonly tag: 'path' | 'rect' | 'circle' | 'line' | 'polyline' | 'polygon' | 'ellipse';
  readonly attrs: Readonly<Record<string, string>>;
}

/** 아이콘 이름 → 그 아이콘을 이루는 도형들 (그리는 순서 그대로) */
export const ICON_SHAPES: Record<IconName, readonly IconShape[]> = {
${entries}
};
`;

  return {
    filePath: path.join(UI_GENERATED_DIR, 'icons', 'icon-geometry.ts'),
    content: body,
  };
}
