// T1 — tokens/*.json (SSOT #1) → CSS 변수 + TypeScript 타입/프리셋 임베드 생성기
// 사용: pnpm build:tokens
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const tokensDir = join(root, 'tokens')
const outDir = join(root, 'src', 'tokens', 'generated')
mkdirSync(outDir, { recursive: true })

const PRESET_ORDER = ['bootstrap', 'tailwind', 'toss']

const presets = {}
for (const file of readdirSync(tokensDir).filter((f) => f.endsWith('.json'))) {
  const json = JSON.parse(readFileSync(join(tokensDir, file), 'utf8'))
  presets[json.$preset] = json
}

const names = PRESET_ORDER.filter((p) => presets[p])
if (names.length !== PRESET_ORDER.length) {
  throw new Error(`tokens/ 프리셋 누락: 기대 ${PRESET_ORDER}, 실제 ${Object.keys(presets)}`)
}

const px = (n) => `${n}px`

// a) vars-<preset>.css — :root[data-theme] (스펙 §5 형식) + [data-theme] (ThemeScope div 적용)
for (const name of names) {
  const t = presets[name]
  const lines = []
  for (const [k, v] of Object.entries(t.color)) lines.push(`  --ds-color-${k}: ${v};`)
  lines.push(`  --ds-font-family: ${t.typography.fontFamily};`)
  for (const [k, v] of Object.entries(t.typography.sizes)) lines.push(`  --ds-font-size-${k}: ${px(v)};`)
  for (const [k, v] of Object.entries(t.typography.weights)) lines.push(`  --ds-font-weight-${k}: ${v};`)
  for (const [k, v] of Object.entries(t.radius)) lines.push(`  --ds-radius-${k}: ${px(v)};`)
  for (const [k, v] of Object.entries(t.spacing)) lines.push(`  --ds-spacing-${k}: ${px(v)};`)
  const css = `/* AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT (SSOT: tokens/${name}.json) */\n` +
    `:root[data-theme='${name}'],\n[data-theme='${name}'] {\n${lines.join('\n')}\n}\n`
  writeFileSync(join(outDir, `vars-${name}.css`), css)
}

// b) types.ts — 유니온 타입은 토큰 JSON 키에서 생성
const union = (keys) => keys.map((k) => `'${k}'`).join(' | ')
const ref = presets[names[0]]
const typesTs = `// AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT (SSOT: tokens/*.json)
export type StylePreset = ${union(names)}
export type ColorToken = ${union(Object.keys(ref.color))}
export type FontSizeToken = ${union(Object.keys(ref.typography.sizes))}
export type FontWeightToken = ${union(Object.keys(ref.typography.weights))}
export type RadiusToken = ${union(Object.keys(ref.radius))}
export type SpacingToken = ${union(Object.keys(ref.spacing))}

export interface DesignTokens {
  $preset: StylePreset
  color: Record<ColorToken, string>
  typography: {
    fontFamily: string
    baseSize: number
    scale: number
    sizes: Record<FontSizeToken, number>
    weights: Record<FontWeightToken, number>
  }
  radius: Record<RadiusToken, number>
  spacing: Record<SpacingToken, number>
}

export const presets: Record<StylePreset, DesignTokens> = ${JSON.stringify(
  Object.fromEntries(names.map((n) => [n, presets[n]])),
  null,
  2,
)}
`
writeFileSync(join(outDir, 'types.ts'), typesTs)

// c) theme.ts — CSS 변수명 헬퍼
const themeTs = `// AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT
import type { ColorToken } from './types'

export const cssVar = (t: ColorToken) => \`var(--ds-color-\${t})\`
`
writeFileSync(join(outDir, 'theme.ts'), themeTs)

// 완료 조건 검증: 프리셋당 CSS 변수 키 목록 동일
const varKeys = (name) =>
  readFileSync(join(outDir, `vars-${name}.css`), 'utf8')
    .match(/--ds-[a-z0-9-]+(?=:)/g)
    .sort()
    .join(',')
const first = varKeys(names[0])
for (const name of names.slice(1)) {
  if (varKeys(name) !== first) throw new Error(`변수 세트 불일치: ${names[0]} vs ${name}`)
}

console.log(`build:tokens OK — presets: ${names.join(', ')} → src/tokens/generated/`)
